### PR TITLE
Fix noise images generated for '--num' > 1 in Stable Diffusion sample

### LINKED ISSUE #405: stable diffusion 1.5 generates noise image with "--num"
**Environment**
Windows 11
openvino 2024.1.0
12900K+A770

**Command**
build\Release\stable_diffusion.exe --num 4 -d GPU.1 -m models/dreamlike_anime_1_0_ov

**Description**
image
With arg "--num 4",  noise image was coming out starting from second round generation.

### PR DESCRIPTION
**Pull request by yatarkan**
Fixes #405

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Review by Wovchena — APPROVED** [review]

File: image_generation/stable_diffusion_1_5/cpp/src/main.cpp [hunk 1]
```diff
@@ -368,11 +368,11 @@ int32_t main(int32_t argc, char* argv[]) try {
...
     ov::Tensor text_embeddings = text_encoder(models, positive_prompt, negative_prompt);
 
-    std::shared_ptr<Scheduler> scheduler = std::make_shared<LMSDiscreteScheduler>();
-    scheduler->set_timesteps(num_inference_steps);
-    std::vector<std::int64_t> timesteps = scheduler->get_timesteps();
-
     for (uint32_t n = 0; n < num_images; n++) {
+        std::shared_ptr<Scheduler> scheduler = std::make_shared<LMSDiscreteScheduler>();
+        scheduler->set_timesteps(num_inference_steps);
+        std::vector<std::int64_t> timesteps = scheduler->get_timesteps();
```
Comment (ilya-lavrenov) [inline image_generation/stable_diffusion_1_5/cpp/src/main.cpp:374]: do we need the same for LCM ?
as I  see scheduler is created outside of the loop https://github.com/yatarkan/openvino.genai/blob/a21a9fcb7f1fbac5de239743567a677c63d4ab70/image_generation/lcm_dreamshaper_v7/cpp/src/main.cpp#L343-L348

Comment (yatarkan) [reply image_generation/stable_diffusion_1_5/cpp/src/main.cpp:374]: Just double checked LCM sample - it does work as is now with '--num' > 1 and generates normal images without moving scheduler inside the loop. I assume it is due to different implementations of `LMSDiscreteScheduler` and `LCMScheduler`

Comment (Wovchena) [reply image_generation/stable_diffusion_1_5/cpp/src/main.cpp:374]: I'm merging this since it resolves the issue. @yatarkan can you align the schedulers in a different PR
